language: node_js
node_js:
  - "12"

dist: trusty

branches:
  only:
  - main

notifications:
  email: false

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jobs: 
  include: 
    - stage: tests
      script:
      - npm run test
    - stage: deploy
      script:
        - npm run build
      deploy:
        provider: pages
        strategy: git
        skip_cleanup: true
        token: $GITHUB_TOKEN
        local_dir: dist
        on:
          branch: master